export const Content = {
    SETTINGS_HINT: "Open settings",
    SELECT_ROLES: "Select role",
    LOG_OUT_DIALOG: "Log out",
    BALANCE: "Balance",
    AMOUNT: "Amount",
    RECIPIENT: "Recipient",
    ABOUT_QR: "QR code will be displayed here",
    SEND_NOTIFICATION: "Send a payment email notification",
    TERMS: "I agree with terms, conditions, and privacy policy",
    ACCOUNT_EXIST: "Already have an account? ",
    ACCOUNT_NOT_EXIST: "Don't have an account? ",
    SELECT_FROM: "From",
    SELECT_TO: "To",
}