spring:
  application:
    name: notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: -----
    password: -----
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          starttls:
            enable: true
          auth: true
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: com.qpay.libs.models


email-template:
  payment-merchant:
    subject: "Payment Notification"
    text: "You received a payment of %s. Thank you for using our service."
  payment-customer:
    subject: "Payment Notification"
    text: "You have completed the payment for the %s. Thank you for using our service."
  report:
    subject: "Transactions Report"
    text: "You received a transaction report from %s to %s. Thank you for using our service."

email:
  enabled: true

broker:
  groups:
    payment-group: payment_group_1
    report-group: report_group1
  topics:
    payment-topic: payment
    report-topic: report