spring:
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8083
  error:
    include-message: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

email:
  enabled: false

broker:
  groups:
    payment-group: local_payment_group_1
    transaction-group: local_transaction_group1
  topics:
    payment-topic: local_payment
    report-topic: local_report