broker:
  topics:
    report-topic: report

spring:
  application:
    name: transaction-history
  data:
    web:
      pageable:
        default-page-size: 25
        max-page-size: 50
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1