spring:
  data:
    mongodb:
      database: qpay
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8084
  error:
    include-message: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

broker:
  topics:
    report-topic: local_report