spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        default_schema: TEST_WALLETS
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:h2:mem:qpay_test
    username: admin
    password: password
    driverClassName: org.h2.Driver
  flyway:
    schemas: TEST_WALLETS
  cloud:
    openfeign:
      client:
        config:
          notification:
            url: http://localhost:8183
            logger-level: basic
          transactionHistory:
            url: http://localhost:8184
            logger-level: basic

broker:
  topics:
    payment-topic: local_payment