CREATE TABLE IF NOT EXISTS customers
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(32),
    email      VARCHAR(32) UNIQUE,
    password   VARCHAR(32),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);