CREATE TABLE IF NOT EXISTS merchants
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(32),
    email      VARCHAR(32),
    password   VARCHAR(32),
    wallet_id  BIGINT,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);