CREATE TABLE IF NOT EXISTS wallets
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(32),
    balance    NUMERIC(12,2),
    user_id    BIGINT,
    user_type  VARCHAR(32),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE INDEX IF NOT EXISTS user_id_index ON wallets(user_id);