object Versions {

    const val FLYWAY = "9.22.2"
    const val POSTGRESQL = "42.6.0"
    const val H2 = "2.2.224"
    const val WIREMOCK = "3.3.1"
    const val JAKARTA_VALIDATION = "3.0.0"
    const val KAFKA = "3.1.1"
    const val ZXING_CORE = "3.5.3"
    const val ZXING_JAVASE = "3.5.3"
    const val SPRING_CLOUD = "2023.0.0"
    const val JSON_WEBTOKEN = "0.11.5"
    const val JJWT_IMPL = "0.11.5"
    const val JJWT_JACKSON = "0.11.5"
    const val OPENFEIGN = "4.1.0"
    const val CIRCUIT_BREAKER = "3.0.4"
    const val ACTUATOR = "3.2.3"
    const val GATLING_APP = "3.9.0"
    const val GATLING_CHARTS = "3.10.5"
    const val I_TEXT_PDF = "8.0.3"
}