webclient:
  services:
    notification-manager:
      base-url: http://localhost:8183
    transaction-history-manager:
      base-url: http://localhost:8184

spring:
  application:
    name: payment
  flyway:
    schemas: payment
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_schema: payment
    hibernate:
      ddl-auto: validate
