spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/qpay
    username: admin
    password: password
  jpa:
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    com.example.api.client: DEBUG

server:
  port: 8082
  error:
    include-message: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

broker:
  topics:
    payment-topic: local_payment