spring:
  application:
    name: api-gateway
  cloud:
      gateway:
        routes:
          - id: user-manager
            uri: lb://users
            predicates:
              - Path=/api/v1/customers/**,/api/v1/merchants/**
            filters:
              - CircuitBreaker=GatewayCircuitBreaker
              - Authentication
          - id: payment-manager
            uri: lb://payment
            predicates:
              - Path=/api/v1/wallets/**,/api/v1/payments/**
            filters:
              - CircuitBreaker=GatewayCircuitBreaker
              - Authentication
          - id: qr-generator
            uri: lb://qr-generator
            predicates:
              - Path=/api/v1/qrcode/**
            filters:
              - CircuitBreaker=GatewayCircuitBreaker
              - Authentication
          - id: auth-manager
            uri: lb://auth
            predicates:
              - Path=/api/v1/auth/signIn
            filters:
              - CircuitBreaker=GatewayCircuitBreaker
          - id: transaction-history
            uri: lb://transaction-history
            predicates:
              - Path=/api/v1/transactions/**
            filters:
              - CircuitBreaker=GatewayCircuitBreaker
              - Authentication

resilience4j:
  circuitbreaker:
    instances:
      GatewayCircuitBreaker:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 30
        wait-duration-in-open-state: 10s
  timelimiter:
    configs:
      default:
        timeout-duration: 10s