spring:
  application:
    name: api-gateway
  cloud:
      gateway:
        routes:
          - id: user-manager
            uri: http://localhost:8081
            predicates:
              - Path=/api/v1/customers/**,/api/v1/merchants/**
            filters:
              - name: CircuitBreaker
                args:
                  name: GatewayCircuitBreaker
              - Authentication
          - id: payment-manager
            uri: http://localhost:8082
            predicates:
              - Path=/api/v1/wallets/**,/api/v1/payments/**
            filters:
              - name: CircuitBreaker
                args:
                  name: GatewayCircuitBreaker
              - Authentication
          - id: qr-generator
            uri: http://localhost:8085
            predicates:
              - Path=/api/v1/qrcode/**
            filters:
              - name: CircuitBreaker
                args:
                  name: GatewayCircuitBreaker
              - Authentication
          - id: auth-manager
            uri: http://localhost:8086
            predicates:
              - Path=/api/v1/auth/signIn
            filters:
              - name: CircuitBreaker
                args:
                  name: GatewayCircuitBreaker

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: TIME_BASED
        sliding-window-size: 1
        failure-rate-threshold: 50
        minimum-number-of-calls: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          seconds: 10
        permitted-number-of-calls-in-half-open-state: 5
    instances:
      GatewayCircuitBreaker:
        base-config: default