spring:
  application:
    name: api-gateway
  cloud:
      gateway:
        routes:
          - id: user-manager
            uri: http://localhost:8081
            predicates:
              - Path=/api/v1/customers/**,/api/v1/merchants/**
            filters:
              - Authentication
          - id: payment-manager
            uri: http://localhost:8082
            predicates:
              - Path=/api/v1/wallets/**,/api/v1/payments/**
            filters:
              - Authentication
          - id: qr-generator
            uri: http://localhost:8085
            predicates:
              - Path=/api/v1/qrcode/**
            filters:
              - Authentication
          - id: auth-manager
            uri: http://localhost:8086
            predicates:
              - Path=/api/v1/auth/signIn