server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

webclient:
  services:
    user-manager:
      base-url: http://localhost:8086