server:
  port: 8081
spring:
  application:
    name: users
  flyway:
    schemas: users
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_schema: users
    hibernate:
      ddl-auto: validate