spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/qpay
    username: admin
    password: password
  jpa:
    show-sql: true
  cloud:
    openfeign:
      client:
        config:
          auth:
            url: http://localhost:8086
            logger-level: basic

logging:
  level:
    com.example.api.client: DEBUG

server:
  port: 8081
  error:
    include-message: always