name: Java CI with Gradle

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Compile
        run: ./gradlew classes

      - name: Unit testing
        run: ./gradlew test

      - name: Integration testing
        run: ./gradlew integrationTest